NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('news.urls')),
    path('sign/', include('allauth.urls')),
    path('', include('sign.urls')),
]


news/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import News, PostList, Search, PostCreate, PostEdit, PostDelete, CategoryDetailView, subscribe, unsubscribe

app_name = 'news'
urlpatterns = [
    # path('', News.as_view(), name='post_list'),
    path('', cache_page(60)(News.as_view()), name='post_list'),
    # path('<int:pk>/', PostList.as_view(), name='post'),
    path('<int:pk>/', cache_page(60*5)(PostList.as_view()), name='post'),
    path('search/', Search.as_view(), name='post_search'),
    path('add/', PostCreate.as_view(), name='post_add'),
    path('<int:pk>/edit/', PostEdit.as_view(), name='post_edit'),
    path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
    path('category/<int:pk>/', CategoryDetailView.as_view(), name='category'),
    path('subscribe/<int:pk>', subscribe, name='subscribe'),
    path('unsubscribe/<int:pk>', unsubscribe, name='unsubscribe'),
]

sign/urls.py
from django.urls import path
from .views import IndexView
from .views import upgrade_me

app_name = 'sign'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('upgrade/', upgrade_me, name='upgrade'),
]

templates/protect/index.html
{% extends "main.html" %}

{% block content %}
<h2>
 Страница авторизованного пользователя {{request.user.username}}
</h2>

<div>
 Здравствуйте,  {{user.username}}!
<div>

<a class="btn btn-primary" type="submit" href="/sign/logout/">
 Выйти
</a>
 <a class="btn btn-primary" type="submit" href="/news">
 Перейти к новостям
</a>
{% if is_not_author %}

<a class="btn btn-primary" type="submit" href="{% url 'sign:upgrade' %}">
 Хочу вступить в группу авторов проекта!
</a>
{% else %}
<h3>
 Вы в группе авторов!
</h3>
{% endif %}
{% endblock content %}