NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('news.urls')),
    path('sign/', include('allauth.urls')),
    path('', include('sign.urls')),
]


news/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import News, PostList, Search, PostCreate, PostEdit, PostDelete, CategoryDetailView, subscribe, unsubscribe

app_name = 'news'
urlpatterns = [
    # path('', News.as_view(), name='post_list'),
    path('', cache_page(60)(News.as_view()), name='post_list'),
    # path('<int:pk>/', PostList.as_view(), name='post'),
    path('<int:pk>/', cache_page(60*5)(PostList.as_view()), name='post'),
    path('search/', Search.as_view(), name='post_search'),
    path('add/', PostCreate.as_view(), name='post_add'),
    path('<int:pk>/edit/', PostEdit.as_view(), name='post_edit'),
    path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
    path('category/<int:pk>/', CategoryDetailView.as_view(), name='category'),
    path('subscribe/<int:pk>', subscribe, name='subscribe'),
    path('unsubscribe/<int:pk>', unsubscribe, name='unsubscribe'),
]

news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.db.models import Sum
from django.urls import reverse
from django.core.cache import cache


class Author(models.Model):
    ratingAuthor = models.IntegerField(default=0)
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)

    def update_rating(self):
        postRat = self.post_set.all().aggregate(ratingPost=Sum('ratingPost'))
        pRat = 0
        pRat += postRat.get('ratingPost')

        commentRat = self.authorUser.comment_set.all().aggregate(ratingComment=Sum('ratingComment'))
        cRat = 0
        cRat += commentRat.get('ratingComment')

        commentPostRat = Comment.objects.filter(commentPost__author=self).values('ratingComment').aggregate(
            ratingComment=Sum('ratingComment'))
        cPRat = 0
        cPRat += commentPostRat.get('ratingComment')

        # print('pRat =', pRat * 3, 'cRat = ', cRat, 'cPRat = ', cPRat)

        self.ratingAuthor = pRat * 3 + cRat + cPRat
        self.save()

    def __str__(self):
        return f'{self.authorUser}'


class Category(models.Model):
    category = models.CharField(max_length=255, unique=True)
    subscribers = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return self.category

    @property
    def subscribe_count(self):
        return self.subscribers.all().count()

class CategorySubscribers(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subscriber = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.category}"



class Post(models.Model):
    NEWS = 'NW'
    ARTICLE = 'AR'
    TYPE_CHOICES = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья')
    )
    type = models.CharField(max_length=2, choices=TYPE_CHOICES, default=ARTICLE)
    timePost = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    textPost = models.TextField()
    ratingPost = models.IntegerField(default=0)

    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    category = models.ManyToManyField(Category, through='PostCategory')

    def like(self):
        self.ratingPost += 1
        self.save()

    def dislike(self):
        self.ratingPost -= 1
        self.save()

    def preview(self):
        return self.textPost[:124] + '...'

    def __str__(self):
        return f'{self.title} {self.textPost}'

    def get_absolute_url(self):
        return f'/news/{self.id}'

    def get_category_type(self):
        return self.get_type_display()

    def get_category(self):
        return [c.category for c in self.category.all()]

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        cache.delete(f'post-{self.pk}')


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    textComment = models.TextField()
    timeComment = models.DateTimeField(auto_now_add=True)
    ratingComment = models.IntegerField(default=0)

    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        try:
            return self.commentPost.author.authorUser.username
        except:
            return self.commentUser.username

    def like(self):
        self.ratingComment += 1
        self.save()

    def dislike(self):
        self.ratingComment -= 1
        self.save()

news/forms.py
from django.forms import ModelForm
from .models import Post
from django import forms


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['type', 'title', 'textPost', 'author', 'category']
        labels = {
            'type': 'Нововсть/статья',
            'title': 'Заголовок',
            'textPost': 'Текст новости/статьи',
            'author': 'Автор',
            'category': 'Категория'
        }
        widgets = {
            'type': forms.Select(attrs={
                'class': 'form-control',
            }),
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите заголовок'
            }),
            'textPost': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Текст вашей нововсти или статьи'
            }),
            'author': forms.Select(attrs={
                'class': 'form-control',
            }),
        }

news/views.py
from datetime import timedelta, datetime

from django.conf import settings
from django.core.exceptions import PermissionDenied
from django.core.mail import EmailMultiAlternatives
from django.http import HttpResponseRedirect
from django.utils import timezone

from django.contrib.auth.decorators import login_required
from django.db.models import QuerySet
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy, resolve, reverse
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.core.paginator import Paginator  # импортируем класс, позволяющий удобно осуществлять постраничный вывод
from django.contrib.auth.mixins import LoginRequiredMixin, \
    PermissionRequiredMixin  # миксин, проверка наличия аутентификации пользователя
from .filters import PostFilter
from .forms import PostForm
from .models import Post, Author, Category
from django.core.cache import cache


# DEFAULT_FROM_EMAIL = settings.DEFAULT_FROM_EMAIL
class News(ListView):
    model = Post
    template_name = 'news.html'
    context_object_name = 'news'
    queryset = Post.objects.order_by('-timePost')
    paginate_by = 10

    def get_queryset(self) -> QuerySet(any):
        post_filter = PostFilter(self.request.GET, queryset=Post.objects.all())
        return post_filter.qs.order_by('-timePost')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = timezone.localtime(timezone.now())  # добавим переменную текущей даты time_now
        context['filter'] = PostFilter(self.request.GET,
                                       queryset=self.get_queryset())  # вписываем фильтр в контекст
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)  # создаём новую форму, забиваем в неё данные из POST-запроса
        if form.is_valid():
            form.save()
        return super().get(request, *args, **kwargs)


class PostList(DetailView):
    model = Post
    template_name = 'post.html'
    context_object_name = 'post'
    queryset = Post.objects.all()

    def get_object(self, *args, **kwargs):
        obj = cache.get(f'post-{self.kwargs["pk"]}', None)
        if not obj:
            obj = super().get_object(queryset=self.queryset)
            cache.set(f'post-{self.kwargs["pk"]}', obj)

        return obj


class Search(ListView):
    model = Post
    template_name = 'search.html'
    queryset = Post.objects.order_by('-timePost')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset())
        return context


class PostCreate(PermissionRequiredMixin, CreateView):
    template_name = 'post_create.html'
    form_class = PostForm
    permission_required = 'news.add_Post'
    context_object_name = 'news'

    def post(self, request, *args, **kwargs):

        form = self.form_class(request.POST)
        self.object = form.save()
        self.category_list = self.object.category.all()

        for category in self.category_list:

            for sub in category.subscribers.all():
                html_content = render_to_string(
                    'mail.html',
                    {
                        'user': sub,
                        'post': self.object,
                    }
                )

                msg = EmailMultiAlternatives(
                    subject=f'{self.object.title}',
                    body=self.object.textPost,
                    from_email='kuchinsk93@yandex.ru',
                    to=[f'{sub.email}'],
                )
                msg.attach_alternative(html_content, "text/html")  # добавляем html
                msg.send()  # отсылаем
                print(html_content)

        return HttpResponseRedirect(self.get_success_url())

    def form_valid(self, form):

        super().form_valid(form)
        author = Author.objects.get(authorUser_id=self.request.user.id)
        yesterday = datetime.now() - timedelta(days=1)
        post_day = Post.objects.filter(author=author, timePost__gt=yesterday).count()

        if post_day > 3:
            return redirect('news:post_list')


class PostEdit(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = 'post_edit.html'
    form_class = PostForm
    permission_required = 'news.change_Post'

    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Post.objects.get(pk=id)


class PostDelete(DeleteView):
    template_name = 'post_delete.html'
    queryset = Post.objects.all()
    success_url = reverse_lazy('news:post_list')


class AddProduct(PermissionRequiredMixin, CreateView):
    permission_required = 'news.add_post'


class CategoryDetailView(DetailView):
    model = Category
    template_name = 'category.html'
    context_object_name = 'category'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = Category.objects.get(id=self.kwargs['pk'])
        context['subscribers'] = category.subscribers.all()
        return context


def subscribe(request, pk):
    category = Category.objects.get(pk=pk)
    category.subscribers.add(request.user.id)
    return redirect('news:post_list')
    # return HttpResponseRedirect(reverse('category', args=[pk]))


def unsubscribe(request, pk):
    category = Category.objects.get(pk=pk)
    category.subscribers.remove(request.user.id)
    return redirect('news:post_list')
    # return HttpResponseRedirect(reverse('category', args=[pk]))

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block head_title %}{% endblock head_title %}</title>
    </head>
    <body>
        {% block body %}
        {% block content %}
        {% endblock content %}
        {% endblock body %}
        {% block extra_body %}
        {% endblock extra_body %}
    </body>
</html>

templates/category.html
{% extends 'flatpages/default.html' %}

{% block title %}
{{ category }}
{% endblock title %}

{% block content %}

<div class="subscribed">

  {% if user not in subscribers %}
    <p>Хотите получать свежие новости из раздела {{category}}?</p>
        <form action="{% url 'news:subscribe' category.pk %}" method="Post">
            {% csrf_token %}
            <input type="submit" value="Подписаться"/>
        </form>
    {% else %}
    <p>Вы больше не хотите получать свежие новости из раздела {{category}}?</p>
        <form action="{% url 'news:unsubscribe' category.pk %}" method="Post">
            {% csrf_token %}
            <input type="submit" value="Отписаться"/>
        </form>
  {% endif %}


</div>

{% endblock content %}

templates/mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3> Здравствуй, {{ user.username }}! Для вас свежая новость:</h3>
    <h3> {{ post.title }}</h3>
    <p><a href="http://127.0.0.1:8000/{{ post.get_absolute_url }}">{{ post.textPost|truncatechars:50 }}</a></p>
</body>
</html>

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
<link rel="stylesheet" href="assets/css/style.css">

<title>
 NewsPaper
 {% block title %}
 {% endblock title %}
</title>

</head>

<body>
  {% block content %}
  {% endblock content %}

</body>

</html>

templates/news.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
News
{% endblock title %}

{% block content %}
<h1>Свежие новости:</h1>

{% for post in news %}
    <h3 > {{ post.title|censor }} </h3>
    <p> {{ post.textPost|censor|truncatewords:20}} </p>
    <a href="/news/{{post.id}}">Читать далее</a>
    <p> {{ post.author }} {{ post.timePost|date:'d.m.Y' }}
        {% for c in post.category.values %}
            <a href="{% url 'news:category' c.id %}">{{ c.category }}</a>
        {% endfor %}
    </p>
    <a href="{% url 'news:post_edit' post.id %}">Редактировать </a><a href="{% url 'news:post_delete' post.id %}"> Удалить</a>
{% endfor %}
{% include 'paginator.html' %}
{% endblock content %}

templates/paginator.html
{% if is_paginated %}

   {% if page_obj.has_previous %}
       <a href="?page=1">First</a>
       <a href="?page={{ page_obj.previous_page_number }}"> <<< </a>
   {% endif %}

   {% for num in page_obj.paginator.page_range %}
       {% if page_obj.number == num %}
           <a>{{ num }}</a>
       {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
           <a href="?page={{ num }}">{{ num }}</a>
       {% endif %}
   {% endfor %}

   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">>>></a>
       <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
   {% endif %}


{% endif %}

templates/post.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% block title %}
News:
{% endblock title %}

{% block content %}
<h3>{{ post.title|censor }}</h3>
<p>{{ post.timePost }}</p>
<p>{{ post.textPost|censor }}</p>
<p> {{ post.author }} {{ post.timePost|date:'d.m.Y' }}
    {% for c in post.category.values %}
        <a href="{% url 'news:category' c.id %}">{{ c.category }}</a>
    {% endfor %}
</p>

<a href="{% url 'news:post_edit' post.id %}">Редактировать </a><a href="{% url 'news:post_delete' post.id %}"> Удалить</a>
{% endblock content %}

templates/post_create.html
{% extends 'flatpages/default.html' %}

{% block title %}
Post create
{% endblock title %}

{% block content %}

<h3>Создание нововсти или статьи:</h3>

<form method="POST">
 {% csrf_token %}
 {{ form }}
 <input class="btn btn-success" type="submit" value="Add">
</form>

{% endblock content %}

templates/post_delete.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
Post delete
{% endblock title %}

{% block content %}

<h3>Вы уверены что хотите удалить эту нововсть?</h3>

 <div class="card">
     <h3> {{ post.title|censor }} </h3>
     <p> {{ post.textPost|censor|truncatewords:20}} </p>
     <p> {{ post.author }} {{ post.timePost|date:'d.m.Y' }}</p>
 </div>

<form method="POST">
 {% csrf_token %}
    <input class="btn btn-success" type="submit" value="Да, удалить">
</form>

{% endblock content %}

templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block title %}
Post edit
{% endblock title %}

{% block content %}

<h3>Редактирование новости/статьи:</h3>

<form method="POST">
 {% csrf_token %}
 {{ form }}
   <input class="btn btn-success" type="submit" value='Добавить изменения'>
</form>

{% endblock content %}

templates/search.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
News
{% endblock title %}

{% block content %}
<h1>Поиск по новостям:</h1>

<form class="form-label" method="GET">
   {{ filter.form }} <hr>
   <input class="btn btn-primary btn-lg" type="submit" value="Найти">
</form>

{% for post in filter.qs %}
    <h3> {{ post.title|censor }} </h3>
    <p> {{ post.textPost|censor|truncatewords:20}} </p>
    <p> {{ post.author }} {{ post.timePost|date:'d.m.Y' }} </p>
{% endfor %}

{% include 'paginator.html' %}

{% endblock content %}

templates/week_mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<h3>Посты за неделю для {{subscriber}}</h3>
    {% for post in posts %}
        <h3><a href="http://127.0.0.1:8000/{{ post.get_absolute_url }}">{{ post.title|truncatechars:50 }}</a><h3>
        <p>{{ post.textPost|truncatechars:100 }}</p>
    {% endfor %}
</body>
</html>